exchange: binance
symbols: ["BTC/USDT", "ETH/USDT"]
timeframe: "1h"
paper:
  starting_balance_eur: 10000.0
  fee_bps: 10
  slippage_bps: 5
risk:
  max_position_fraction: 0.25
  max_daily_loss_fraction: 0.05
  circuit_breaker_drawdown: 0.10
strategy:
  name: "sma_cross"
  params:
    fast: 20
    slow: 50
data:
  lookback_limit: 1500
  cache_minutes: 0
tuning:
  n_trials: 50
  direction: "maximize"
schedule:
  retrain_hour_utc: 2
network:
  timeout_ms: 20000
  max_retries: 5
  backoff_base_ms: 500
  user_agent: TraderBot/1.0
proxies:
  http:
  https:
